### ISSUE TITLE
Plotting genes with their appropriate lengths and gaps

### ISSUE THREAD

**Issue by TMiguelT** [VisBOL/visbol-js#109]
This possibly relates to #31. Can visbol-js draw SBOL glyphs like gene markers, but to-scale, with the right lengths, positions and spacing? The SBOL language doesn't really seem to concern itself with showing accurate positions, but is there some way to make visbol-js work like this?

**Comment by cjmyers** [comment]
Thanks for your question.  Currently VisBol does not really show accurate positions on a DNA strand.  There are other sequence level visualization tools more focused on this.  The goal of VisBol and SBOL Visual to give a higher level functional view essentially.  However, I suggest you open an issue on the SBOL Visual issue tracker to have the community consider your request:

https://github.com/SynBioDex/SBOL-visual/issues <https://github.com/SynBioDex/SBOL-visual/issues>

Thanks again.

**Comment by TMiguelT** [comment]
That's a shame. Thanks for getting back to me nonetheless.
