### ISSUE TITLE
crash in minified version

### ISSUE THREAD

**Issue by FilippoPolo** [VisBOL/visbol-js#110]
Hi all,

We're using visbol-js as part of a compbio tool, and we have problems when attempting to bundle it for production. We are using webpack with a standard production configuration, which includes minification through uglifyjs.

After minification, the function named "fire" in svg.js no longer works. The error we see in the browser console is as follows: TypeError: "e is not a constructor"

In this case, that 'e' is actually the constructor for CustomEvent, which the minifier is supposed to have shortened. In debug, "new CustomEvent" works normally; in production, "new e" fails with the error above.

I've tried upgrading webpack and uglifyjs to the latest versions, but the problem persists.

**Comment by PrashantVaidyanathan** [comment]
@cjmyers 
Just for some additional context. We are facing this issue only when visbol-js is minified. When we use it normally, this issue doesn't persist. 

To recreate this issue (at-least based on how we encounter it), if you minify visbol-js using uglify-js you should encounter this issue. Please let us know if you require any additional details to recreate this error.

**Comment by cjmyers** [comment]
Hmm, this one is really outside my wheelhouse.  @udp @3ach do either of you have any thoughts?

**Comment by cjmyers** [comment]
@udp @3ach James/Zach: do either of you have any thoughts on this?

**Comment by udp** [comment]
Would it be possible to send your minified svg.js?  I tried running uglifyjs on svg.js alone, and CustomEvent is still CustomEvent.

**Comment by udp** [comment]
[svg_and_minified.zip](https://github.com/VisBOL/visbol-js/files/3668228/svg_and_minified.zip)

**Comment by FilippoPolo** [comment]
I believe it only happens if you bundle first, i.e. with webpack. It looks like some kind of bad interaction with the module system.

**Comment by FilippoPolo** [comment]
We couldn't figure this out, but it turns out the issue is no longer present in the most recent version of Visbol. We're just going to use that.

**Comment by cjmyers** [comment]
That's good.
