### ISSUE TITLE
Bug with multiple level visBOL diagrams

### ISSUE THREAD

**Issue by cjmyers** [VisBOL/visbol-js#14]
Some multiple level visBOL diagrams fail to render (see BBa_J95007, for example). Fixed in synbiohub. The bug is visBOL cannot display an diagram with the same part more than once included in the display list. I now filter to prevent this going to visBOL, but visBol needs to have this fixed too.  It might actually now.  Needs testing.

**Comment by 16zzundel5** [comment]
Same as issue #18
