### ISSUE TITLE
Merge getDisplayList and soToGlyphType into VisBol and remove from SynBioHub

### ISSUE THREAD

**Issue by cjmyers** [VisBOL/visbol-js#18]
Need to do this carefully as they may both have differences at this point.  Key ones in getDisplayList are use of config to remap the URI in SynBioHub and the fix for cycle of constraints.

**Comment by 16zzundel5** [comment]
Solving this would solve cycle of constraints, so I'm closing that issue.

**Comment by 16zzundel5** [comment]
I think I've merged the getDisplayLists in visBOL
