### ISSUE TITLE
The example does not work using the Chrome browser 

### ISSUE THREAD

**Issue by goksel** [VisBOL/visbol-js#2]
It has worked with Safari and Firefox.

**Comment by udp** [comment]
Hi, are you trying to run the example locally?  Chrome doesn't allow XHR for file:// URLs, so if you run the example as a local file it won't be able to load the dependencies.

It works for me if I access the example via HTTP (local webserver).

**Comment by udp** [comment]
Seems to work correctly in Chrome.  Please open a new issue if there are any further issues.
