### ISSUE TITLE
Generic boxes should be above/below not on the line

### ISSUE THREAD

**Issue by cjmyers** [VisBOL/visbol-js#23]
This will allow one to determine if it is inline or reverseComplement

**Comment by 16zzundel5** [comment]
How can this be distinguished from an Operator, then?

**Comment by cjmyers** [comment]
Good question.  Maybe we could make operators square and generic boxes rectangle (approx. two squares abutted in size).

**Comment by 16zzundel5** [comment]
Operators should be square per the spec, so this would be technically correct. I am worried that the two glyphs would be still pretty close to identical visually. What about something that included a question mark à la Unicode boxes?

![img_0920](https://cloud.githubusercontent.com/assets/3093325/25900661/19afde76-358c-11e7-88b1-d6fe347b4bf9.jpg)

Something like one of these?

**Comment by cjmyers** [comment]
This is a subject of on-going debate in SBOLv group.  Not sure what will end up happening here.  In Visbol, we can use color to make more clear distinction or labels, but this is not official SBOLv which prefers to not specify color, label, size, etc.  

One other point is the boxes should touch and not hover over the line.  SBOLDesigner has hover, which according to Jake is wrong.

**Comment by 16zzundel5** [comment]
And looking in the SBOL 1.0.0 specification, the user-defined glyph _is_ the rectangle and the operator is the square, hm. I'll get both fixed.

**Comment by cjmyers** [comment]
I see confusion now.  Above/below seems to imply hover.  What is meant is on top or under the line, but always touching.

**Comment by 16zzundel5** [comment]
Fixed per latest commit and published as version 1.3.4
