### ISSUE TITLE
Operator vs. User defined glyph

### ISSUE THREAD

**Issue by 16zzundel5** [VisBOL/visbol-js#24]
Nitpicky question:
The araR_araR shown in this image represents an operator. Based on the SBOL visual specification 1.0.0 , the operator symbol is represented as a square shape and not a rectangle shape. A rectangle shape represents a user defined symbol and the square shape represents an operator.

This issue is redundant across the Bacillus subtilis collection.

![](https://cloud.githubusercontent.com/assets/7537729/24920136/60a23932-1ea3-11e7-8687-1fa92967f2cd.png)

[from @tramyn]

**Comment by 16zzundel5** [comment]
There are actually two issues. 1) the operator glyph is a rectangle and 2) this is not the operator glyph. I've opened another issue for the first problem. (#25)

**Comment by cjmyers** [comment]
Strange.  I see a different glyph on synbiohub.org

http://synbiohub.org/public/bsu/BO_27632/1

It is a white rectangle hovering above the line.  The issue could be with soToGlyphType.  Please compare yours with the one that was in synbiohub.

**Comment by 16zzundel5** [comment]
The original issue was logged 30 days ago, so it may have been logged before I added the operator glyph. I get the correct image as well.
