### ISSUE TITLE
Operator glyph should be a square, not a rectangle

### ISSUE THREAD

**Issue by 16zzundel5** [VisBOL/visbol-js#25]
Originally raised as part of issue #24 by @tramyn

Currently, the operator glyph is not rendered as a square, but as a rectangle. Per the specification, it should be a square. 

![screen shot 2017-05-10 at 11 21 41 am](https://cloud.githubusercontent.com/assets/3093325/25894205/ddbee538-3572-11e7-951e-fc9b4f97d611.png)

**Comment by cjmyers** [comment]
Should also be touching the line.

**Comment by 16zzundel5** [comment]
Fixed per latest commit.

**Comment by 16zzundel5** [comment]
(And published in version 1.3.4)
