### ISSUE TITLE
Export images as SVG?

### ISSUE THREAD

**Issue by jakebeal** [VisBOL/visbol-js#28]
Is there any way to export instances from the font as SVGs for use in building the SBOLv spec?

**Comment by cjmyers** [comment]
On visbol.org, there is a download tab with SVG as a download option.  Works for me.  Is it causing any problems with you?

**Comment by jakebeal** [comment]
I meant to try to get the individual glyphs, not full constructs.  I'll see if I can kludge that to get ahold of the ones I need, though.

**Comment by zachzundel** [comment]
There is not a way to do this currently, as all the glyph are hand-defined in `font/sbolv`. I am not sure that's really within the scope of this project, so I'm going to close this as a bug.

**Comment by cjmyers** [comment]
Wouldn’t you be able to get the glyphs by creating a ComponentDefinition with no Components/SequenceAnnotations and has the role for the glyph you want.  This should display a single glyph.

**Comment by jakebeal** [comment]
Yes, @cjmyers : that is the kludge that I am planning to do.

**Comment by jakebeal** [comment]
I am having trouble figuring out which roles can trigger some of the glyphs (e.g., polyA, mature-transcript-region).  I also haven't been able to find that table in the code anywhere. Can you please point me to a mapping from SO term to glyph?

**Comment by cjmyers** [comment]
The table is here:

https://github.com/VisBOL/visbol-js/blob/master/lib/soToGlyphType.js

You are also correct that mature transcript region (http://www.sequenceontology.org/browser/current_svn/term/SO:0000233) and polyA (http://www.sequenceontology.org/browser/current_svn/term/SO:0000553) are missing from this table.

Zach: it looks like these entries got lost when you merged the table into VisBol.  Can you check this out and fix it?  The glyphs do exist here:

https://github.com/VisBOL/visbol-js/tree/master/font/sbolv

**Comment by jakebeal** [comment]
Thank you, Chris.  That's just what I need.
