### ISSUE TITLE
Using default colours for promoters, CDSs, RBSs and terminators

### ISSUE THREAD

**Issue by goksel** [VisBOL/visbol-js#4]
It would be useful to show basic components in colour when you submit a SBOL document.
For example:
promoters: light green
RBS:Dark green
CDS:Blue
Terminator: Red

A suggestion form Figure 7 in http://dl.acm.org/citation.cfm?id=2631921

**Comment by udp** [comment]
https://github.com/VisBOL/visbol-js/commit/9c200c3762ca470328d19d4b99ea7dc572600c20
