### ISSUE TITLE
5' Overhang Site

### ISSUE THREAD

**Issue by nathanwilk7** [VisBOL/visbol-js#48]
http://sbolstandard.org/wp-content/uploads/2017/10/SBOLVisual_Specification_2_0_0.pdf, page 26

**Comment by nathanwilk7** [comment]
3' is the just the mirror image

**Comment by cjmyers** [comment]
Seems correct, but Dany reports it was flipped.

**Comment by dany-fu** [comment]
Not a codebase issue. Problem resides with SBOLDesigner
