### ISSUE TITLE
Sticky Restriction Site

### ISSUE THREAD

**Issue by nathanwilk7** [VisBOL/visbol-js#49]
http://sbolstandard.org/wp-content/uploads/2017/10/SBOLVisual_Specification_2_0_0.pdf, page 27

**Comment by cjmyers** [comment]
Not showing up.  Perhaps an SO mapping problem

**Comment by dany-fu** [comment]
@cjmyers 
You are correct, this was a SO mapping problem

Another issue here is that there are two sticky restriction sites (5' - SO 1975 and 3' - SO 1976) in the documentation. In the test file you sent, it is only being referred to as CUT (SO - 1975)

**Comment by cjmyers** [comment]
Good point.  This is a bug in SBOLDesigner.  I've logged an issue in the SBOLDesigner issue tracker.  

Let me know when you check in the fix for this mapping problem, and I will test again.

**Comment by cjmyers** [comment]
Fixed
