### ISSUE TITLE
Origin of Replication

### ISSUE THREAD

**Issue by nathanwilk7** [VisBOL/visbol-js#54]
http://sbolstandard.org/wp-content/uploads/2017/10/SBOLVisual_Specification_2_0_0.pdf, page 36

**Comment by zachzundel** [comment]
Verified as missing

**Comment by asadeg02** [comment]
@zachzundel There already exists a file as origin_of_replication.js. 
Looking at the code, I guess the render function in this file, draws the same thing as what this issue is asking for (a circle if boxSize.x equals boxSize.y) So would you mind explaining the difference please?Thanks.

**Comment by zachzundel** [comment]
I'm not sure, maybe it is mis-filed and already exists. I will take a look
at this once I've finished untangling the dependency issue.

**Comment by cjmyers** [comment]
Done
