### ISSUE TITLE
Add support for simple interactions with DNA strand

### ISSUE THREAD

**Issue by cjmyers** [VisBOL/visbol-js#64]
Add support for simple interactions, such as genetic production that connects a CDS to a protein AND inhibition/stimulation that connects a protein to a promoter.

**Comment by dany-fu** [comment]
Looking at the spec, I gather
1) Degradation (p.58)
2) Inhibition (p.59)
3) Process (p.60)
4) Stimulation (p.61)
Am I missing any?

Are there any examples and test files?

**Comment by cjmyers** [comment]
Yes, that is the complete set for now.

The tricky thing about these is that you will now need to deal with ModuleDefinitions, since these only render for them.  Here is an example of inhibition:

https://synbiohub.programmingbiology.org/public/Cello_Parts/AmeR_pAmeR_repression/1 <https://synbiohub.programmingbiology.org/public/Cello_Parts/AmeR_pAmeR_repression/1>

The AmeR_protein glyph should be above the pAmeR promoter glpyh with the inhibition error pointing from the protein to the promoter.

Here is a simulation example:

https://synbiohub.programmingbiology.org/public/Cello_Parts/Ara_AraC_protein_pBAD_activation/1 <https://synbiohub.programmingbiology.org/public/Cello_Parts/Ara_AraC_protein_pBAD_activation/1>

In this case, the Ara_AraC_protein glyph would have a simulation arrow point down to the pBad promoter glyph.

Here is a degradation example:

https://synbiohub.programmingbiology.org/public/Cello_Parts/AmeR_protein_degradation/1 <https://synbiohub.programmingbiology.org/public/Cello_Parts/AmeR_protein_degradation/1>

The Ame_protein glyph would have a degradation arrow leaving it.  It could go in any direction, but I think protein on left and arrow going right might look best.

Here is a process example:

https://synbiohub.programmingbiology.org/public/Cello_Parts/AmeR_protein_production/1 <https://synbiohub.programmingbiology.org/public/Cello_Parts/AmeR_protein_production/1>

The AmeR CDS glyph would have a process arrow pointing up to the AmeR_protein glyph.

For now, we are assuming you will only have ModuleDefinitions with a single Interaction as above.  We are also assuming that the types of objects are fairly simple, as above.

Here is one for extra credit:

https://synbiohub.programmingbiology.org/public/Cello_Parts/Ara_AraC_protein_complex_formation/1 <https://synbiohub.programmingbiology.org/public/Cello_Parts/Ara_AraC_protein_complex_formation/1>

This involves a protein, a small molecule, and a complex.  The protein and small molecule should have process arrows that point to the complex.  The exact layout is not fixed.  One example that might look good is to have the reactants on the left and the product on the right.

**Comment by dany-fu** [comment]
You showed us a diagram when we met in May that had these interactions, could you link that here or email it? We'd like to have a reference for how the interactions and glyphs are positioned in respect to each other

**Comment by cjmyers** [comment]
Figure 28 here is one example:
http://sbolstandard.org/wp-content/uploads/2018/01/BBF-RFC114-SBOL2.2.0.pdf

There are several examples in this paper:
https://pubs.acs.org/doi/pdf/10.1021/acssynbio.7b00459

Here is one from that paper:

![1](https://user-images.githubusercontent.com/3507191/41241289-c39cf01c-6d59-11e8-8985-cbda58e4b54e.png)

**Comment by cjmyers** [comment]
Note that initially we are not doing anything this complex.  The diagram on the left has four interactions in one diagram, but for now, we are going to assume a single interaction in a diagram.  Our stretch goals is rendering diagrams like this, but it is a lot more involved since layout becomes an issue.

**Comment by dany-fu** [comment]
Should the interaction to be rendered on the sequence/circuit or the individual segments below it? Or both?

**Comment by cjmyers** [comment]
It should be rendered with the DNA FunctionalComponent below the protein FunctionalComponent.  In the case of inhibition or stimulation, the arrow should go downwards from the protein to the promoter.  In the case of genetic production, it should go from the CDS up to the protein.

**Comment by asadeg02** [comment]
![inhibition-interaction](https://user-images.githubusercontent.com/32320836/41801403-570eb0be-7648-11e8-92a6-c9af30c8055c.png)

Thanks for your quick reply. Above is what we have for inhibition right now, but our question is should we render interactions like this (As separate segments, assuming that we only deal with simple interactions here, having up to 2 participants and no sharing their participant with each other) or should we add the protein glyph and the inhibition arrow pointing to the promoter above the promote in the sequence that promoter is participating in?
Thanks again.

**Comment by asadeg02** [comment]
![screenshot from 2018-06-22 18-20-35](https://user-images.githubusercontent.com/32320836/41801540-37435180-7649-11e8-947b-2ca5c5394f05.png)
Just to clarify more on the issue, above is the rendering for the sbol file containing inhibition before adding the support to render interactions of type inhibition. my question is that should I add protein and inhibition arrow above the promoter in the pAmeR segment or should I do it the way I am doing right now(in a separate box or segment)? I'm asking this question because the way we need to take care of the layout and segment padding would be different depending on the approach we choose.
Thanks

**Comment by cjmyers** [comment]
The protein will not be on a line, so the first diagram you sent is correct, and I think it looks good.
