### ISSUE TITLE
Restriction enzyme site and protease site glyphs are reversed

### ISSUE THREAD

**Issue by cjmyers** [VisBOL/visbol-js#67]
The restriction enzyme site glyph should be the protease site glyph and vice versa.

**Comment by cjmyers** [comment]
They are still showing up reversed, and ribonecleae site is missing.

**Comment by dany-fu** [comment]
@cjmyers 
Ribonuclease SO term was missing from soToGlyphType file. Easy fix.

If they are still flipped, then I think they were not reversed originally. Just to be clear
1) Restriction enzyme glyph should have a straight stem 
![screen shot 2018-05-03 at 15 05 39](https://user-images.githubusercontent.com/7750862/39597469-83df6084-4ee3-11e8-85d8-5057e92a5e8b.png)

2) Rubonuclease glyph should have a sqiggly stem
![screen shot 2018-05-03 at 15 05 47](https://user-images.githubusercontent.com/7750862/39597485-8b7d5724-4ee3-11e8-8765-b37762277a76.png)

3) Protease glyph should have a loopy stem 
![screen shot 2018-05-03 at 15 05 43](https://user-images.githubusercontent.com/7750862/39597487-8e8ed51e-4ee3-11e8-91c1-751f771ff559.png)

Is this correct?

**Comment by cjmyers** [comment]
Yes, this is correct.

**Comment by cjmyers** [comment]
Fixed
