### ISSUE TITLE
Hovering info box can't follow horizontal scrolling

### ISSUE THREAD

**Issue by cjmyers** [VisBOL/visbol-js#71]
Particularly large constructs often don't fit horizontally onto the screen. To look at such a construct, one has to scroll to the right, which is fine. The black "info box" that pops up when one hovers over a glyph, however, gets stuck maxing out at the window width and cannot follow the scroll.

This prevents the user from seeing "pop-up" information about large constructs, because it appears way off to the left of where the mouse cursor is, often entirely off the left side of the window.

Reported by @jakebeal

**Comment by dany-fu** [comment]
@jakebeal, do you have an example circuit on SBH that shows this or instructions on how to replicate this bug?

**Comment by jakebeal** [comment]
How to replicate with a not-so-big device:
https://synbiohub.org/public/iGEM_2016_interlab/Medium_2016Interlab/1

Make your browser window narrower than the circuit diagram; hover your mouse over BBa_B0015

**Comment by dany-fu** [comment]
I'm not convinced that this is a visbol issue. The tooltip is added in Visbol but the positioning, I think, should be a CSS issue addressed on SBH.

**Comment by cjmyers** [comment]
@udp @zachzundel : can you guys comment on this one?

**Comment by cjmyers** [comment]
@udp as requested, I've assigned this issue with the VisBol Tooltip to you to have a look at.

**Comment by cjmyers** [comment]
Possible a CSS issue.  Need to check with James (@udp) on this one.

**Comment by cjmyers** [comment]
Fixed in SynBioHub CSS in Version 1.5.4.
