### ISSUE TITLE
SO:0000035 rendered as generic engineered region

### ISSUE THREAD

**Issue by cjmyers** [VisBOL/visbol-js#72]
Reported by @jakebeal

Riboswitches (role=SO:0000035) are being rendered in SynBioHub as a generic Engineered Region even though they are a child of SO:0000834 (Mature Transcript Region) and as such should get the "Non-Coding RNA Gene" glyph.

**Comment by cjmyers** [comment]
Not sure if this one is still a problem.  Should check.

**Comment by jvscholz** [comment]
fixed by #107
