### ISSUE TITLE
Change how composite part is found

### ISSUE THREAD

**Issue by dany-fu** [VisBOL/visbol-js#91]
Because this information is more easily available in the SBOL, update the SBOL parser and create a new `composite: true/false` flag in displayList

**Comment by dany-fu** [comment]
@cjmyers is there a method in sboljs that detects which ComponentDefinition is the topmost level (the circuit)? Arezoo and I just looked into this issue and noticed that parsing the composite from the SBOL would not be more efficient than what is currently implemented if there is no way to tell which is the top level CD.

**Comment by cjmyers** [comment]
I don't think this is necessary.  To determine if something is a composite, you simply can do:

foreach CD 
  foreach Component in CD
    if (definition of Component has components) then this Component is a Composite

**Comment by cjmyers** [comment]
Completed.
